sudo: required
language: node_js
node_js:
- 6.6.0
env:
  global:
  - DB_USERNAME=dumbledore
  - NODE_ENV=production
  - secure: Ke/C4rYMzG6UBW/fYDIKEZ8u/xRyBxvRxXdiKApxk17kfQWSqChTVfz34ZVaNP44e9EFjIkzyx9YIQaKBpBn8VDlRZAkogHE9ERN3iH3GZZim67u8xz0ucp/t3dTe3Gma13bXC4D4nCVlbhPmYL2Esa/iveN+6JW51vMCncp9VMD9zGQegoq/t0uvo/yGvoPUfnFBVb4SjxiJiRW0l4JCdZFeb3BW/J107elIMrrQ0ypKS+Pjg72P87G89EH5L/IyiEzzEk5FGkWkSQ4wl0ZSNSWuj4UEDYdYzICgt91BrgPiRb37jkz5PEtnoISvqAXqMpcj4xVsdH+6ihM1ykESl4JqdR1IIQQLrKtB0dpBd+ul8OuDwP3y+syOc5eoixl7OR0e6YwXBfEVWUcEEzoIzZ5fDQwqQBmPAgzuwXnZX9jXzPcTuYQ/LDbJ/61KVjQ4cqQz3dyRL7MGnX2BvDGAm3Z/AP/RCzZzeOY8Sku97xOP/QQFxEOzYX4ls9V2ho2X0wjXQ/xFuGn8KlDjwjVsMN6Yl4otigfL90wbqCnhp0Z5r1yKT3y4BUYbttnjA8CuDx30ruCje6GUNf3lKFYXbLH+qVpgXp0ALwqIdPjgdOSz4RHmF8aeVnLojD4qFLzi/gl52Y1zR+YC6um+3xhiyAaAN+Jqijo05yKsbRTLlM=

